{{- if and .Values.backup.enabled (not .Values.backup.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "subnetory.backup.claimName" . }}
  labels:
    {{- include "subnetory.labels" . | nindent 4 }}
    app.kubernetes.io/component: backup
  {{- if eq .Values.backup.persistence.resourcePolicy "keep" }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.backup.persistence.accessModes | nindent 4 }}
  {{- if .Values.backup.persistence.storageClass }}
  storageClassName: {{ .Values.backup.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.backup.persistence.size }}
{{- end }}
