{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "subnetory.postgresql.fullname" . }}
  labels:
    {{- include "subnetory.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: postgresql
      port: {{ .Values.postgresql.service.port }}
      targetPort: postgresql
      protocol: TCP
  selector:
    {{- include "subnetory.postgresql.selectorLabels" . | nindent 4 }}
{{- end }}
