apiVersion: v2
name: subnetory
description: Mono-replica Helm chart for Subnetory
type: application
version: 0.1.11
appVersion: "0.8.9"
kubeVersion: ">=1.34.0-0"
home: https://github.com/Subnetory/subnetory
sources:
  - https://github.com/Subnetory/subnetory
maintainers:
  - name: Subnetory
